# Generated by Django 5.2.3 on 2025-06-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=10, unique=True)),
                ('long_url', models.URLField(max_length=1048)),
                ('last_access', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
