# Generated by Django 5.2.3 on 2025-06-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='long_url',
            new_name='url',
        ),
    ]
